### ISSUE TITLE
Request Errors

### ISSUE THREAD

**Issue by triksmelb** [luluhoc/radarr-mass-delete#6]
Hoping someone can decipher the below message and tell me what it means. When I run node app.js the app deleted around 60 movies but gave me 100's of these errors. Just wondering what they mean and if its an issue with omdb, the app or permissions or if its normal.
thanks

`RequestError: Error: connect ECONNREFUSED 104.20.134.15:443
    at new RequestError (/usr/local/lib/node_modules/npm/radarr/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/npm/radarr/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/npm/radarr/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/npm/radarr/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/npm/radarr/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  cause: Error: connect ECONNREFUSED 104.20.134.15:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '104.20.134.15',
    port: 443
  },
  error: Error: connect ECONNREFUSED 104.20.134.15:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '104.20.134.15',
    port: 443
  },
  options: {
    uri: 'https://private.omdbapi.com/?apikey=myprivateapikey=tt1077368',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
`

**Comment by luluhoc** [comment]
This repository is depreciated please use https://github.com/luluhoc/home-cinema-toolkit
